###
GET http://localhost:3000/api/v1/user/1


###
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "username": "superusedr",
    "password": "123456"
}
###
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "id_user_admin": 1,
    "name": "juana perez",
    "username": "juana22",
    "password": "4321",
    "administrator": 1
}
###
GET http://localhost:3000/api/v1/devices

###
POST http://localhost:3000/api/v1/devices
Content-Type: application/json

{
    "user_id": 3,
    "device_name": "iphone de bob",
    "ipv4": "192.168.10.14",
    "scopes": ["ENCENDER_LED", "APAGAR_LED"],
    "led": 3
}
###
GET http://localhost:3000/api/v1/actions

###
POST http://localhost:3000/api/v1/actions
Content-Type: application/json

{
    "description": "Encender el foco de la sala",
    "ledsLedId": 1,
    "usersUserId": 2
}

###
POST http://localhost:3000/api/v1/actions
Content-Type: application/json

{
    "description": "Apagar el foco de la sala",
    "ledsLedId": 1,
    "usersUserId": 3
}

###
GET http://localhost:3000/api/v1/currentDateTime

###
GET http://localhost:3000/api/v1/users
###
GET http://localhost:3000/api/v1/leds
###
GET http://localhost:3000/api/v1/devices/count

###
GET http://localhost:3000/api/v1/leds/count

###
#DASHBOARD
GET http://localhost:3000/api/v1/actions/count?userId=3&ledId=1&startDate=2023-01-01&endDate=2023-12-31&
###
GET http://localhost:3000/api/v1/actions/count

###
GET http://172.20.10.6:3000/api/v1/apagarCocina

###
GET http://localhost:3000/api/v1/prenderSala

###
GET http://localhost:3000/api/v1/prenderDormitorio