###
GET http://localhost:3000/api/v1/user/100


###
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "username": "superusedr",
    "password": "123456"
}
###
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "id_user_admin": 3,
    "name": "juan perez",
    "username": "juan22",
    "password": "4321",
    "administrator": 0
}
###