-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2023-11-17 12:28:18.038

-- tables
-- Table: AUTHORIZATION
CREATE TABLE AUTHORIZATION (
    AUTHORIZATION_ID int  NOT NULL,
    SCOPES_SCOPE_ID serial  NOT NULL,
    LEDS_LED_ID serial  NOT NULL,
    DEVICES_DEVICE_ID serial  NOT NULL,
    CONSTRAINT AUTHORIZATION_pk PRIMARY KEY (AUTHORIZATION_ID)
);

-- Table: DEVICES
CREATE TABLE DEVICES (
    DEVICE_ID serial  NOT NULL,
    DEVICE_NAME varchar(50)  NOT NULL,
    IPV4 varchar(16)  NOT NULL,
    GRANTED_CONN boolean  NOT NULL,
    USERS_USER_ID serial  NOT NULL,
    CONSTRAINT DEVICES_pk PRIMARY KEY (DEVICE_ID)
);

-- Table: H_ACTION
CREATE TABLE H_ACTION (
    ACTION_ID serial  NOT NULL,
    DESCRIPTION varchar(50)  NOT NULL,
    DATETIME datetime  NOT NULL,
    LEDS_LED_ID serial  NOT NULL,
    USERS_USER_ID serial  NOT NULL,
    CONSTRAINT H_ACTION_pk PRIMARY KEY (ACTION_ID)
);

-- Table: LEDS
CREATE TABLE LEDS (
    LED_ID serial  NOT NULL,
    LED_NAME varchar(100)  NOT NULL,
    ESP_PIN int  NOT NULL,
    CONSTRAINT LEDS_pk PRIMARY KEY (LED_ID)
);

-- Table: SCOPES
CREATE TABLE SCOPES (
    SCOPE_ID serial  NOT NULL,
    SCOPE_NAME varchar(200)  NOT NULL,
    CONSTRAINT SCOPES_pk PRIMARY KEY (SCOPE_ID)
);

-- Table: USERS
CREATE TABLE USERS (
    USER_ID serial  NOT NULL,
    NAME varchar(100)  NOT NULL,
    PASSWORD varchar(50)  NOT NULL,
    USERNAME varchar(100)  NOT NULL,
    ADMIN bit(1)  NOT NULL,
    CONSTRAINT USERS_pk PRIMARY KEY (USER_ID)
);

-- foreign keys
-- Reference: ACTION_LEDS (table: H_ACTION)
ALTER TABLE H_ACTION ADD CONSTRAINT ACTION_LEDS FOREIGN KEY ACTION_LEDS (LEDS_LED_ID)
    REFERENCES LEDS (LED_ID);

-- Reference: ACTION_USERS (table: H_ACTION)
ALTER TABLE H_ACTION ADD CONSTRAINT ACTION_USERS FOREIGN KEY ACTION_USERS (USERS_USER_ID)
    REFERENCES USERS (USER_ID);

-- Reference: AUTHORIZATION_DEVICES (table: AUTHORIZATION)
ALTER TABLE AUTHORIZATION ADD CONSTRAINT AUTHORIZATION_DEVICES FOREIGN KEY AUTHORIZATION_DEVICES (DEVICES_DEVICE_ID)
    REFERENCES DEVICES (DEVICE_ID);

-- Reference: AUTHORIZATION_LEDS (table: AUTHORIZATION)
ALTER TABLE AUTHORIZATION ADD CONSTRAINT AUTHORIZATION_LEDS FOREIGN KEY AUTHORIZATION_LEDS (LEDS_LED_ID)
    REFERENCES LEDS (LED_ID);

-- Reference: DEVICES_USERS (table: DEVICES)
ALTER TABLE DEVICES ADD CONSTRAINT DEVICES_USERS FOREIGN KEY DEVICES_USERS (USERS_USER_ID)
    REFERENCES USERS (USER_ID);

-- Reference: entity_1_SCOPES (table: AUTHORIZATION)
ALTER TABLE AUTHORIZATION ADD CONSTRAINT entity_1_SCOPES FOREIGN KEY entity_1_SCOPES (SCOPES_SCOPE_ID)
    REFERENCES SCOPES (SCOPE_ID);

-- End of file.

